# Generated by Django 6.0 on 2026-01-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatex', '0003_utilizationreport_reportproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Donate Platform', max_length=200)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('registration_open', models.BooleanField(default=True)),
                ('require_ngo_approval', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
    ]
