# Generated by Django 6.0 on 2026-01-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donatex', '0006_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
    ]
