# Generated by Django 6.0 on 2026-01-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donatex', '0011_campaign_campaignparticipation'),
    ]

    operations = [
    ]
