# Generated by Django 6.0 on 2026-02-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatex', '0013_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otps',
            },
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
