# Generated by Django 6.0 on 2026-02-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donatex', '0014_otp_remove_donation_payment_method_delete_payment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignparticipation',
            unique_together=set(),
        ),
    ]
