# Generated by Django 6.0 on 2026-02-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatex', '0015_alter_campaignparticipation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
